### ISSUE TITLE
The drop rate on the wiki doesn't reflect the input drop rate

### ISSUE THREAD

**Issue by ghost** [ThePharros/probability-calculator#5] opened 2023-02-11 20:58 UTC
The drop rate on the wiki doesn't reflect the input drop rate

![image](https://user-images.githubusercontent.com/14812476/218280261-b78bec09-9a55-4c19-8d2c-5652c9afb030.png)
![image](https://user-images.githubusercontent.com/14812476/218280473-6f9b25ef-ee7f-4f63-b465-d6170bd38e21.png)
![image](https://user-images.githubusercontent.com/14812476/218280371-0047eeb1-c64f-46d0-b527-1fa0c371958b.png)

**Comment by hawkins** [comment] 2024-02-08 03:42
Your first drop rate shows a drop rate of 2% (1/50). Recall that the drop rate represents the probability of the event, measured from 0 to 1 - so 1 represents 100%, 0 represents 0%. Therefore, 0.02 represents 2/100, or 2%. What you want is 1/5000, or 0.0002. 

You can also save yourself the headache and just enter the fraction - `1/5000` instead of trying to do the decimal math yourself. The plugin supports that just fine

**Comment by ThePharros** [comment] 2024-04-19 14:07
As @hawkins explained, the wiki value is the percentage, not the decimal value out of 1. And yeah the plugin lets you just type the fraction and it will auto-calculate the decimal value for ya. Closing as this is working as intended.

**Closed as completed by ThePharros** 2024-04-19 14:07 UTC
